"""agregar tabla usuarios y relacion con tareas

Revision ID: 142d938d996d
Revises: 
Create Date: 2026-09-06 17:19:02.870375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142d938d996d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('usuarios',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('nombre', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.add_column('tareas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    with op.batch_alter_table("tareas") as batch_op:
        batch_op.create_foreign_key(
            "fk_tareas_usuario",
            "usuarios",
            ["usuario_id"],
            ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_column('tareas', 'usuario_id')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
